var UnifyAudio = {

    REQUIRED_TAG: "UnifyAudio",
    PROP_SHEET: "UnifySheet",
    PROP_ENTRY: "UnifyEntry",
    PROP_GROUP: "UnifyGroup",

    getUserProperty: function(event, key) {
        for (var i = 0; i < event.userProperties.length; i++) {
            if (event.userProperties[i].key === key)
                return event.userProperties[i].value;
        }
        return null;
    },

    hasTag: function(event, tag) {
        for (var i = 0; i < event.tags.length; i++) {
            if (event.tags[i].name === tag)
                return true;
        }
        return false;
    },

    validateEvent: function(event) {
    if (!this.hasTag(event, this.REQUIRED_TAG))
        return false;

    var sheet = this.getUserProperty(event, this.PROP_SHEET);

    if (!sheet || sheet.trim() === "") {
        studio.system.print("[UnifyAudio] Warning: Event '" + event.name + 
            "' is tagged UnifyAudio but missing UnifySheet property. Skipping.");
        return false;
    }

    return true;
    },

    collectEvents: function() {
        var sheets = {};
        var allEvents = studio.project.model.Event.findInstances();

        for (var i = 0; i < allEvents.length; i++) {
            var event = allEvents[i];

            if (!this.validateEvent(event))
                continue;

            var sheetName = this.getUserProperty(event, this.PROP_SHEET).trim();
            var groupName = this.getUserProperty(event, this.PROP_GROUP);
            groupName = groupName ? groupName.trim() : null;

            // fall back to event name if UnifyEntry not set
            var entryProperty = this.getUserProperty(event, this.PROP_ENTRY);
            var entryName = entryProperty && entryProperty.trim() !== ""
                ? entryProperty.trim()
                : event.name.replace(/\s+/g, "");

            if (!sheets[sheetName])
                sheets[sheetName] = { ungrouped: [], groups: {} };

            var entryData = {
                name: entryName,
                path: event.getPath()
            };

            if (groupName) {
                if (!sheets[sheetName].groups[groupName])
                    sheets[sheetName].groups[groupName] = [];
                sheets[sheetName].groups[groupName].push(entryData);
            } else {
                sheets[sheetName].ungrouped.push(entryData);
            }
        }

        return sheets;
    },

    generateClass: function(sheetName, sheetData) {
        var lb = "\r\n";
        var out = "";

        out += "// Auto-generated by UnifyAudio — do not edit manually" + lb;
        out += "using UnityEngine;" + lb;
        out += "using FMODUnity;" + lb;
        out += "using UnifyAudio;" + lb;
        out += lb;
        out += "[CreateAssetMenu(menuName = \"UnifyAudio/EventCollection/" + sheetName + "\")]" + lb;
        out += "public class " + sheetName + " : UnifyEventCollection" + lb;
        out += "{" + lb;

        // ungrouped entries first
        for (var i = 0; i < sheetData.ungrouped.length; i++) {
            out += "    public EventReference " + sheetData.ungrouped[i].name + ";" + lb;
        }

        // grouped entries
        var groups = Object.keys(sheetData.groups);
        for (var g = 0; g < groups.length; g++) {
            var groupName = groups[g];
            var entries = sheetData.groups[groupName];

            if (sheetData.ungrouped.length > 0 || g > 0)
                out += lb;

            out += "    [Header(\"" + groupName + "\")]" + lb;

            for (var e = 0; e < entries.length; e++) {
                out += "    public EventReference " + entries[e].name + ";" + lb;
            }
        }

        out += "}" + lb;

        return out;
    },

    export: function() {
        var sheets = this.collectEvents();
        var sheetNames = Object.keys(sheets);

        if (sheetNames.length === 0) {
            studio.system.print("[UnifyAudio] No events found with UnifyAudio tag. " +
                "Make sure events are tagged and have UnifySheet and UnifyEntry properties set.");
            return;
        }

        var outputPath = studio.system.getText(
            "Output folder path (absolute, e.g. C:/MyProject/Assets/Audio/Sheets)",
            ""
        );

        if (!outputPath || outputPath.trim() === "") {
            studio.system.print("[UnifyAudio] Export cancelled — no output path provided.");
            return;
        }

        outputPath = outputPath.trim();

        var exported = 0;

        for (var i = 0; i < sheetNames.length; i++) {
            var sheetName = sheetNames[i];
            var content = this.generateClass(sheetName, sheets[sheetName]);
            var filePath = outputPath + "/" + sheetName + ".cs";

            var file = studio.system.getFile(filePath);
            if (!file) {
                studio.system.print("[UnifyAudio] Error: Could not create file object for: " + filePath);
                continue;
            }

            if (!file.open(studio.system.openMode.WriteOnly)) {
                studio.system.print("[UnifyAudio] Error: Could not open file for writing: " + filePath);
                continue;
            }

            if (!file.writeText(content)) {
                studio.system.print("[UnifyAudio] Error: Failed to write to file: " + filePath);
                file.close();
                continue;
            }

            file.close();

            studio.system.print("[UnifyAudio] Exported: " + filePath);
            exported++;
        }

        studio.system.print("[UnifyAudio] Done — " + exported + " sheet(s) exported.");
    }
};

studio.menu.addMenuItem({
    name: "UnifyAudio\\Export Audio Data Sheets",
    isEnabled: function() {
        return true;
    },
    execute: function() {
        UnifyAudio.export();
    }
});